### ISSUE TITLE
rel8 1.4.0.0 does not build with opaleye 0.9.7.0

### ISSUE THREAD

**Issue by elldritch** [circuithub/rel8#265]
This combination of package versions is permitted by rel8's bounds:

https://github.com/circuithub/rel8/blob/5686bd87947ba97adbe9bcf4b77c85b539326950/rel8.cabal#L30

Trying to build this combination of package versions results in:

```
src/Rel8/Aggregate.hs:88:18: error:
    • Couldn't match type ‘Maybe
                             (Opaleye.AggrOp, [Opaleye.OrderExpr], Opaleye.AggrDistinct)’
                     with ‘Opaleye.Aggr’
      Expected: (Opaleye.Aggr, Opaleye.PrimExpr)
        Actual: (Maybe
                   (Opaleye.AggrOp, [Opaleye.OrderExpr], Opaleye.AggrDistinct),
                 Opaleye.PrimExpr)
    • In the first argument of ‘f’, namely
        ‘(tuplize <$> aggregator, input expr)’
      In the second argument of ‘(<$>)’, namely
        ‘f (tuplize <$> aggregator, input expr)’
      In the expression:
        output <$> f (tuplize <$> aggregator, input expr)
   |
88 |     output <$> f (tuplize <$> aggregator, input expr)
   |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

This is probably because of the internal imports in this module:

https://github.com/circuithub/rel8/blob/5686bd87947ba97adbe9bcf4b77c85b539326950/src/Rel8/Aggregate.hs#L24-L27

https://github.com/circuithub/rel8/blob/5686bd87947ba97adbe9bcf4b77c85b539326950/src/Rel8/Aggregate.hs#L80-L91

I'm not sure there's anything that can be done about this now. We would love to upgrade to 1.4.1.0, but unfortunately we are blocked by the presence of #228, and there is not yet a release that includes the fix for #228.

**Comment by ocharles** [comment]
I've published a revision for 1.4 that adds `< 0.9.7.0`. Does that help?

**Comment by elldritch** [comment]
Yes, this has resolved our issue. Thank you! I was not aware of the revisions system in Hackage.
